### PR TITLE
composer: Nette 2.3 is out, add missing Nette\Reflection

### PR DESCRIPTION
**Pull request by TomasVotruba**
- Also, I'd remove all unused packages from `require-dev`. Looks like only Nette\Utils and Nette\Bootstrap are really needed.

- Todo: complete Tracy\Tracy for panel as well (after comments)

### CODE REVIEW

**Comment by fprochazka** [comment]
I apreciate your help, but please don't waste your time on this maintenance thing. I wanna do this myself in a specific way.

**Comment by TomasVotruba** [comment]
I see. Could you at least fix so I don't have to complete missing dependencies manually?

**Comment by hrach** [comment]
@fprochazka seems like expressed david's attitude. Not a long ago you were claiming that we should train our contributors to do it the right way. However, today I totally miss what is  the "specific way" and what is wrong.

**Comment by fprochazka** [comment]
@TomasVotruba yes, I will do that as soon as possible.

**Comment by fprochazka** [comment]
@hrach I'm happy to accept code contributions, but I don't think non-maintainers should be fixing "details" like composer, travis,... :)

**Pull request closed without merging**
